### ISSUE TITLE
URLManager method don't spread the escapeAmp parameter in a nested method call

### ISSUE THREAD

**Issue by ahew** [entando/entando-core#12]
In the class [URLManager](https://github.com/entando/entando-core/blob/master/engine/src/main/java/com/agiletec/aps/system/services/url/URLManager.java), in row 125, there is an invocation of

`return this.createUrl(requiredPage, requiredLang, params, true, null);`

without passing the parameter "escapeAmp".

Probably the correct code is

`return this.createUrl(requiredPage, requiredLang, params, escapeAmp, null);`

**Comment by eugeniosant** [comment]
Thanks Elia :)
