### ISSUE TITLE
GUI fragment

### ISSUE THREAD

**Issue by romarco3** [entando/entando-core#13]
I have used a portal example with myportal plugin.
I received this error in front end.

The fragment 'jacms_content_viewer' of widget 'content_viewer' is not available

Thank you
Marco

![entando1](https://cloud.githubusercontent.com/assets/13051081/8357309/9b8d6164-1b5a-11e5-9a81-39e93220b5b2.png)

**Comment by MEM2677** [comment]
Hi Marco!
It seems you have a corrupted db ~ the message displayed means that the system does not find the code of the widget in the table 'gui fragment' of the *Port database.
The 'content viewer' is composed by 13 different entries in this table and the lack of any of these will produce the error you are experiencing.
You might consider to 1) backup your database and 2) to restore this table to its original state, unless you have carried on extensive customization, in which case you have to carefully introduce your modifications step by step.
