### ISSUE TITLE
Gravatar feature problem

### ISSUE THREAD

**Issue by mbolzan** [entando/entando-core#25]
Also without using the Entando Avatar Plugin, it seems the avatar feature is integrated in the core, without possibility to disable from entando admin ui.

My opinion there a defect into the UserAvatarAction class because there is not a catch on the new URL step, because when you set your ide without internet connection, that class throws an UnknownHostException, this happens often when you are behind a proxy.

Adding a catch (UnknownHostException.. could be a usefull tip.

**Comment by eugeniosant** [comment]
Hi Marco,
This issue is already solved by commit https://github.com/entando/entando-core/commit/ceb06fb148d2aa80efcf2b65308787f859678a01
You'll find this improvement in the next stable release of Entando.
Eu
