### ISSUE TITLE
struts2 library upgrade

### ISSUE THREAD

**Issue by engbmsdev** [entando/entando-core#39]
Currently Endando uses struts v.2.3.16.3 that is affected by several vulnerabilities ([see here](https://struts.apache.org/docs/security-bulletins.html)).

Is it planned an upgrade of the library in next releases of entando?

Thanks!

**Comment by eugeniosant** [comment]
Thanks for the reminder. To fix these issues, the next release (in november) the project will be updated with a new version of Struts2

**Comment by eugeniosant** [comment]
The new version of Entando (4.3.1) has been updated with Struts2 version 2.5.10.1
