### ISSUE TITLE
Demo project does not compile

### ISSUE THREAD

**Issue by mgiammarco** [entando/entando-core#439]
Hello,
I have followed quick start guide, I have created a project using:

 mvn archetype:generate -Dfilter=entando-archetype-portal-bootstrap

I have tried to launch with mvn clean jetty:run but I get:

 Execution generate-liverebel-xml of goal org.zeroturnaround:jrebel-maven-plugin:1.1.3:generate-liverebel-xml failed: A required class was missing while executing org.zeroturnaround:jrebel-maven-plugin:1.1.3:generate-liverebel-xml: org/apache/commons/io/FileUtils
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.zeroturnaround:jrebel-maven-plugin:1.1.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/mgiammarco/.m2/repository/org/zeroturnaround/jrebel-maven-plugin/1.1.3/jrebel-maven-plugin-1.1.3.jar
[ERROR] urls[1] = file:/home/mgiammarco/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[2] = file:/home/mgiammarco/.m2/repository/org/codehaus/plexus/plexus-utils/1.4.1/plexus-utils-1.4.1.jar
[ERROR] urls[3] = file:/home/mgiammarco/.m2/repository/commons-io/commons-io/1.4/commons-io-1.4.jar
[ERROR] urls[4] = file:/home/mgiammarco/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]

**Comment by mgiammarco** [comment]
I have solved the problem going to .m2/repository folder and deleting all commons-* subfolders so maven download again all jars.
Please note anyway that it is very strange because I am a java developer and I use maven all the day and the other projects I build did not require this workaround.

**Comment by joewhite101** [comment]
We'll be updating the docs in the next couple of weeks. I've updated that particular line to point to the newer example.

It is odd that clearing an apache jar would let the build work. If you run into it again let us know.
