### ISSUE TITLE
Security issue (phishing)

### ISSUE THREAD

**Issue by engbmsdev** [entando/entando-core#45]
Hi all,
after the login process on front-end form, the `Autenticator` class redirects the user to `returnUrl` parameter without check his value (see [here](https://github.com/entando/entando-core/blob/master/portal-ui/src/main/java/com/agiletec/aps/system/services/controller/control/Authenticator.java#L83)).

An attacker can share an url like this:
`http://www.mywebsite.it/mysite/en/login.page?returnUrl=http%3A%2F%2Fwww.maliciouswebsite.com&redirectflag=1`

How can I fix this?

**Comment by eugeniosant** [comment]
Sorry for the late reply, first of all thank you for the feedback.

We confirm the problem mentioned. The solution is to replace the parameter "returnURL" with a "returnPageCode" that indicates the code of the landing page, and the redirection would be managed server-side by the control of this parameter (the existence of the page in the portal in first instance).

In any case, for the next versions of entando we planned to integrate the library ESAPI issued by OWASP,  to overcome a large part of the possible security issues.
