### ISSUE TITLE
Fresh installation

### ISSUE THREAD

**Issue by Aminshoshtaryzadeh** [entando/entando-core#532]
I have a problem with installation and i tried to connect with Entando company, but no one is answering and i don't know why. 
I'm trying to install fresh piece but there is no widget and plugin in it,i have connected console to freshly data base, update Entando version 5.1.0 core,component and archetype into maven and then locally run it but its completely blank console.
need help...

**Comment by Aminshoshtaryzadeh** [comment]
i have followed both link:
https://docs.entando.com/
https://github.com/entando/entando-core/wiki/Getting-Started

**Comment by joewhite101** [comment]
Hi @Aminshoshtaryzadeh can you paste what you're getting in the terminal once you have launched your Entando app? Are you getting any errors?

**Comment by Aminshoshtaryzadeh** [comment]
Hi @joewhite101 
there is no error coming. when i'm opening the widget part its empty.
i have tried to update it manually one by one from entando-component but still not getting any.
by the way this is what i'm getting in the terminal

2018-07-30 15:13:51.817 - INFO  - org.entando.entando.apsadmin.system.resource.E
ntandoPluginLabelListener - EntandoPluginLabelListener summary: 8 plugin detecte
d (0 under development)
[INFO] Initializing Spring FrameworkServlet 'springDispatcher'
[INFO] Started o.e.j.m.p.JettyWebAppContext@151ab2b9{/firstwebsite,[file:/C:/Dev
app/new_project/firstwebsite/src/main/webapp/, file:/C:/Devapp/new_project/first
website/target/tmp/entando-misc-less-5_1_0-SNAPSHOT_war1/, file:/C:/Devapp/new_p
roject/firstwebsite/target/tmp/entando-portal-ui-5_1_0-SNAPSHOT_war2/, file:/C:/
Devapp/new_project/firstwebsite/target/tmp/entando-plugin-jpseo-5_1_0-SNAPSHOT_w
ar3/, file:/C:/Devapp/new_project/firstwebsite/target/tmp/entando-plugin-jpinfin
ispan-5_1_0-SNAPSHOT_war4/, file:/C:/Devapp/new_project/firstwebsite/target/tmp/
entando-admin-console-5_1_0-SNAPSHOT_war5/],AVAILABLE}{file:/C:/Devapp/new_proje
ct/firstwebsite/src/main/webapp/}
[WARNING] !RequestLog
[INFO] Started ServerConnector@6a5754f5{HTTP/1.1}{0.0.0.0:8080}
[INFO] Started @62295ms
[INFO] Started Jetty Server
[INFO] Starting scanner at interval of 5 seconds.

**Comment by Aminshoshtaryzadeh** [comment]
as far as i understood from this if i want to add new plugins which are available in entando-component, i have to add them manually on the pom.xml file.
am i correct?
i saw the entando-ux-packages which has variety of widgets, so if i needed some kind of widgets i should follow above instruction?

**Comment by Aminshoshtaryzadeh** [comment]
@joewhite101 Thank you for full explanation.
my last question is how I can upload those plugins which doesn't have dependency tag?
for example: "entando-plugin-jpphotogallery"

**Comment by joewhite101** [comment]
Hi @Aminshoshtaryzadeh 

They are normal maven dependencies. If you open the pom file of the dependency you want to use you'll see the artifact and group id to use. For example, for photo gallery look in this file for the values to use:
https://github.com/entando/entando-components/blob/master/plugins/entando-plugin-jpphotogallery/pom.xml

For a general maven understanding on dependencies.
https://maven.apache.org/pom.html#Dependencies
