### ISSUE TITLE
Automatically Logout user issue

### ISSUE THREAD

**Issue by Aminshoshtaryzadeh** [entando/entando-core#773]
Hi all,
I have installed a fresh entando version 5.0.2 on ubuntu server, the platform work fine but the issue is when I want to add data like creating widget or cms content,module and etc the platform automatically logout me and showing the login page.

**Comment by joewhite101** [comment]
Hi @Aminshoshtaryzadeh 

We haven't been able to reproduce this one. Do you have any more details on your setup? Are you running using Jetty/Derby for your dev environment?

Try adding this command to your startup if you're using Jetty: 
`-Djetty.reload=manual`

That will prevent jetty from automatically restarting and clearing your session.

**Comment by Aminshoshtaryzadeh** [comment]
I have tried the command and restart the platform same thing is happening.
i have monitoring the server, the issue is when you click on any item in admin console the jetty server is restarting and after restart it gives me the below message for login on terminal:

"
 System property [org.owasp.esapi.opsteam] is not set
System property [org.owasp.esapi.devteam] is not set
Attempting to load ESAPI.properties via file I/O.
Attempting to load ESAPI.properties as resource file via file I/O.
Not found in 'org.owasp.esapi.resources' directory or file not readable: /opt/entando/website/ESAPI.properties
Not found in SystemResource Directory/resourceDirectory: .esapi/ESAPI.properties
Not found in 'user.home' (/root) directory: /root/esapi/ESAPI.properties
Loading ESAPI.properties via file I/O failed. Exception was: java.io.FileNotFoundException
Attempting to load ESAPI.properties via the classpath.
SUCCESSFULLY LOADED ESAPI.properties via the CLASSPATH from '/ (root)' using current thread context class loader!
SecurityConfiguration for Validator.ConfigurationFile.MultiValued not found in ESAPI.properties. Using default: false
Attempting to load validation.properties via file I/O.
Attempting to load validation.properties as resource file via file I/O.
Not found in 'org.owasp.esapi.resources' directory or file not readable: /opt/entando/website/validation.properties
Not found in SystemResource Directory/resourceDirectory: .esapi/validation.properties
Not found in 'user.home' (/root) directory: /root/esapi/validation.properties
Loading validation.properties via file I/O failed.
Attempting to load validation.properties via the classpath.
validation.properties could not be loaded by any means. fail. Exception was: java.lang.IllegalArgumentException: Failed to load ESAPI.properties as a classloader resource.
"

**then in admin console it is not showing any content list which is created on the platform.**

**Comment by joewhite101** [comment]
Hi Amin,

Can you send me the whole command you're using to start the platform in your development environment?

**Comment by Aminshoshtaryzadeh** [comment]
first time: "  mvn jetty:run -Djetty.reload=manual "
even i tried : " mvn clean jetty:run -Djetty.reload=manual "
but for now only : " mvn clean jetty:run "

**Comment by joewhite101** [comment]
Ok. One of the first two should be correct for this case. Which archetype did you use to create the project?

**Comment by Aminshoshtaryzadeh** [comment]
just downloaded the entando-archetype-webapp-generic into an empty project as suggested in the official documentation. Didn't make any changes, just automatically configured the latest version.

**Comment by Aminshoshtaryzadeh** [comment]
Solved: by using the second command the problem has been solved. thanks

**still there is an issue which is as follows:**
"System property [org.owasp.esapi.opsteam] is not set
System property [org.owasp.esapi.devteam] is not set
Attempting to load ESAPI.properties via file I/O.
Attempting to load ESAPI.properties as resource file via file I/O.
Not found in 'org.owasp.esapi.resources' directory or file not readable: /opt/entando/pccube-website/ESAPI.properties
Not found in SystemResource Directory/resourceDirectory: .esapi/ESAPI.properties
Not found in 'user.home' (/root) directory: /root/esapi/ESAPI.properties
Loading ESAPI.properties via file I/O failed. Exception was: java.io.FileNotFoundException
Attempting to load ESAPI.properties via the classpath.
SUCCESSFULLY LOADED ESAPI.properties via the CLASSPATH from '/ (root)' using current thread context class loader!
SecurityConfiguration for Validator.ConfigurationFile.MultiValued not found in ESAPI.properties. Using default: false
Attempting to load validation.properties via file I/O.
Attempting to load validation.properties as resource file via file I/O.
Not found in 'org.owasp.esapi.resources' directory or file not readable: /opt/entando/pccube-website/validation.properties
Not found in SystemResource Directory/resourceDirectory: .esapi/validation.properties
Not found in 'user.home' (/root) directory: /root/esapi/validation.properties
Loading validation.properties via file I/O failed.
Attempting to load validation.properties via the classpath.
validation.properties could not be loaded by any means. fail. Exception was: java.lang.IllegalArgumentException: Failed to load ESAPI.properties as a classloader resource.
2019-02-12 14:53:34.209 - ERROR - com.agiletec.plugins.jacms.aps.system.services.content.ContentDAO - Error loading contents status. If you are runing Entando backed by Apache Derby it's a known issue
2019-02-12 14:53:34.214 - ERROR - com.agiletec.plugins.jacms.aps.system.services.content.ContentDAO - Error loading contents status. If you are runing Entando backed by Apache Derby it's a known issue
"

**there is problem with SEO plugin which is not working on Entando version 5.0.2 and gives error.**

**Comment by joewhite101** [comment]
Hi @Aminshoshtaryzadeh those errors can be ignored as related to the SEO plugin. IF you've still got questions on this one please open a new issue.
