### ISSUE TITLE
WidgetType edit stuck on save

### ISSUE THREAD

**Issue by d33pcode** [entando/entando-core#779]
### Steps to reproduce
- open the admin console
- select UX Pattern > Widget
- select a widget
- edit the HTML
- click the _save_ button

### Issue
After clicking the _save_ button, the page loads forever.
Opening the development console and listening to the network requests shows the single `save.action` waiting and a new `update.action` every 1-2 minutes.
Tomcat logs don't print any error.
Refreshing the page shows that the changes are not saved.

### Environment
I have downloaded the Entando v5.0.2 artifact into an empty project, built it with Ant and deployed it inside Tomcat 9 in a Ubuntu 18.04.1 LTS.

---

Do you have any idea of how to solve this issue?
Thank you in advance for the help.

**Comment by joewhite101** [comment]
Hi @d33pcode we're taking a look at this now but haven't been able to reproduce it. Are you getting any logs in your browser console? Which widget are you testing with and what type of edit are you making.

**Comment by d33pcode** [comment]
The browser console is not showing any error.
I've tested all the elements inside the _Widget_ section - adding, removing, updating lines, even just clicking 'save' without any change; the issue is always the same.

**Comment by joewhite101** [comment]
Haven't been able to reproduce this. @d33pcode if you've got more info or are still running into this on master please let us know.
