### ISSUE TITLE
encode sensitive data when storing in database

### ISSUE THREAD

**Issue by rafaeltuelho** [entando/entando-core#782]
There are some sensitive data being stored as clear text in xml format on DB.

**Comment by joewhite101** [comment]
Hi @rafaeltuelho Can you provide some specifics? Which table and type of content are you seeing. User passwords are salted and encrypted.

**Comment by rafaeltuelho** [comment]
@joewhite101 , I'm referring to the xml data stored into `sysconfig` table from `portDataSource`. More specifically the RHPAM credentials. Let's say the RHPAM credentials are entered by an admin person... Maybe these credentials are from a production PAM instance...

**Comment by joewhite101** [comment]
Hey @rafaeltuelho we see that you closed this but we have updated the storage mechanism for those creds with these PRs. Thanks for opening the ticket. If you run into anything else let us know

https://github.com/entando/entando-components/pull/495
https://github.com/entando/entando-core/pull/788
