### ISSUE TITLE
Creating a new Page Model

### ISSUE THREAD

**Issue by e4r** [entando/entando-core#801]
Hey guys,

I am not sure whether this post should be posted here, but it's 2 hours I am trying to understand how to add a Page Model to the select in Page Designer > Pages Tree > _aPage_ > Configure without success.

I can't even find any significant information about this feature, not even in the docs.

Should I add some specific tag in the jsp file?

Thanks

**Comment by joewhite101** [comment]
Hi @e4r to add a new page model you should go to UX Pattern > Page Models adn then hit the add button.
