### ISSUE TITLE
Insufficient input sanitization leads to XSS

### ISSUE THREAD

**Issue by g04tb0y** [entando/entando-core#807]
The Java class in ./portal-ui/src/main/java/org/entando/entando/aps/servlet/XSSRequestWrapper.java does not properly validate and sanitize user supplied data. 
As a suggestion you could use the full ESAPI lib (already imported in code) instead of applying a blacklitst type filter on lines 68-70.

A full disclosure of the vulnerability will be sent to you, if you wish, through a private channel.

**Comment by Kerruba** [comment]
Hello @g04tb0y, thanks for reporting this issue. It would be great if you could provide a full disclosure, you can send more details to l.cherubin@entando.com.

**Comment by joewhite101** [comment]
This is resolved with https://github.com/entando/entando-core/commit/c9946cedcdfe465f68287c8920a68357d84be115
