### ISSUE TITLE
Creating Contact form with attachment

### ISSUE THREAD

**Issue by Aminshoshtaryzadeh** [entando/entando-core#810]
Hi, I am trying to create contact form with attachment for website visitord to send us email with pdf file on the platform but there is an issue with php code for mailing.
Do you have any idea how can I set a contact for with attachment, or there is any sample to use?
I would be appreciate if anyone can help me.
I have tried **web dynamic form** but there is no attachment attribute to use

**Comment by joewhite101** [comment]
Hi @Aminshoshtaryzadeh Can you be a bit more specific on what you're seeing? We don't have any PHP in the codebase.

**Comment by Aminshoshtaryzadeh** [comment]
@joewhite101 
I have installed jpmail plugin which is for set the email sender and smtp configuration.
also i have installed jpwebdynamicform plugin to accept mail from guest user.
I need to have in my contact a form with attachment to guest user be able to send me email by pdf attachment. i couldn't find any plugin to do this for me.
therefore i have tried to create my own contact form , but i think the entando platform is not accepting any php code. i have tried inject into html file , also separated file and link to the simple html widget . but still not working.

**Comment by Aminshoshtaryzadeh** [comment]
@joewhite101 
how we can add a custom form for attachment to either send to specific mail or save attach file into platform folder- ex: creating a folder inside static folder?

**Comment by joewhite101** [comment]
@Aminshoshtaryzadeh You can extend the existing mail plugin to provide an attachment or you could add a new endpoint. In terms of saving the document as an asset you can use the existing endpoints to add a document to the static resources.
