### ISSUE TITLE
keycloak pending

### ISSUE THREAD

**Issue by Tribe-Studios** [entando/entando-core#846]
I've created a 4 node Cluster with the latest rancher, I then followed the instructions in entando docs (https://es-entando.github.io/#why-kubernetes) but I have waited 60+ minutes and keycloak is still pending. Host Os's are Ubuntu 18.04. Would love to know how I can get you more information to help resolve this issue.

**Comment by joewhite101** [comment]
Hey @TechGuyTN you can post questions here and we'll help you out. Are there any errors in the logs that are starting up or any logs that you can send us to take a look at?
