### ISSUE TITLE
GUI FRAGMENTS EDITING PROBLEM ON BACKOFFICE

### ISSUE THREAD

**Issue by davideminnai** [entando/entando-core#9]
When trying to cut&paste fragments from DEFAULT GUI CODE to GUI CODE tab on backoffice, selected content will be wrongly formatted. User NEED to remove all blank spaces manually otherwise fragment won't be load properly.

**Comment by MEM2677** [comment]
I wasn't able to reproduce the issue using Entando 4.2 on *nix and Windows.
I would need the version of Entando, the plugin code and the browser used so to reproduce the issue.
